export enum Category {
  Programming_Languages = 'Programming Languages',
  Backend_Frameworks = 'Backend Frameworks',
  Frontend_Frameworks = 'Frontend Frameworks',
  UI_Libraries = 'UI Libraries',
  Protocols = 'Protocols',
  Architectures = 'Architectures',
  Cloud_Platforms = 'Cloud Platforms',
  Databases = 'Databases',
  DevOps_Tools = 'DevOps Tools',
  Styles = 'Styles',
  State_Management = 'State Management',
  Libraries = 'Libraries',
  Performance_Optimization = 'Performance Optimization',
}
